// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQb6KB9MnKuGtaC6_v23gEANx7IpvJt88',
    appId: '1:640344633860:web:12c745319329102397bb51',
    messagingSenderId: '640344633860',
    projectId: 'a7medkhalaf-spotify-app',
    authDomain: 'a7medkhalaf-spotify-app.firebaseapp.com',
    storageBucket: 'a7medkhalaf-spotify-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2H5Z8rPphtVMGGNY7ZJVYHCOVxKxqLQ',
    appId: '1:640344633860:android:3bc232c8a567552d97bb51',
    messagingSenderId: '640344633860',
    projectId: 'a7medkhalaf-spotify-app',
    storageBucket: 'a7medkhalaf-spotify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd5ZVjR8vhGeNhCIu4UZ5pw2b4qosaXUM',
    appId: '1:640344633860:ios:b49e9925fca4561997bb51',
    messagingSenderId: '640344633860',
    projectId: 'a7medkhalaf-spotify-app',
    storageBucket: 'a7medkhalaf-spotify-app.appspot.com',
    iosBundleId: 'com.example.flutterSpotifyApp',
  );
}
